[package]
name = "ncmc"
publish = false

description = "Command-line NCM audio converter."
keywords    = ["ncm", "ncmc", "cli", "converter", "ncmdump"]

authors    = { workspace = true }
edition    = { workspace = true }
homepage   = { workspace = true }
license    = { workspace = true }
readme     = { workspace = true }
repository = { workspace = true }
version    = { workspace = true }


[dependencies]
anyhow   = { workspace = true }
bpaf     = { workspace = true, features = ["derive"] }
ncm_core = { workspace = true }
ncm_meta = { workspace = true }

[dev-dependencies]
id3      = { workspace = true }
metaflac = { workspace = true }
sha2     = { workspace = true }
testing = { workspace = true }
